[CI] Validate for unique `network_ids` in merchants.yaml (#29)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: Ruby
+name: CI
 
 on:
   push:
@@ -37,5 +37,10 @@ jobs:
       - run: npm install -g ajv-cli
       - name: Validate merchants.yaml
         run: ajv -s lib/yellow_pages/merchants.schema.json -d lib/yellow_pages/merchants.yaml --errors=text
+      - name: Validate unique network_ids in merchants.yaml
+        run: |
+          DUPLICATES="$(yq 'map(.network_ids) | flatten | sort' lib/yellow_pages/merchants.yaml | uniq -cd)"
+          echo "::error ::${DUPLICATES}"
+          if [[ $DUPLICATES ]]; then exit 1; else exit 0; fi
       - name: Validate categories.yaml
         run: ajv -s lib/yellow_pages/categories.schema.json -d lib/yellow_pages/categories.yaml --errors=text
